#!/bin/sh

# Coda from the command line
# Version 1.0
#
# Open Coda or open files in Coda from the command line
#
# (C) Noah Frederick 2011 <http://noahfrederick.com>

###################### CONFIG ######################

# Path to Coda.app
codapath="/Applications/Coda.app"

####################################################

# open_with_coda ():
# Open any number of files with Coda.app
# Files that don't exist will be created
open_with_coda () {
	for arg in "$@"
	do
		if [ ! -f "$arg" ] ; then
			touch "$arg"
		fi
	done
	open -a "$codapath" "$@"
}

# open_coda ():
# Launch Coda.app
open_coda () {
	open "$codapath"
}

# display_help ():
# Show a helpful usage message
display_help () {
	echo "usage: $0 [--help|-h] [<file> ...]"
	echo
	echo '\t--help|-h   show this message'
	echo '\t<file>      file will be opened in Coda.app'
	echo '\t            (omit to launch Coda.app)'
	echo
}

####################################################

if [ $# -gt 0 ]; then
	case "$1" in
		--help|-h)
			display_help
		;;
		*)
			open_with_coda "$@"
		;;
	esac
else 
	open_coda
fi 